export const resources = {
  en: {
    translation: {
      cart: 'Cart',
      'total sum': 'Total sum',
      uah: 'uah',
      errorText: 'The page you are looking for might be renamed, removed, or might never exist. You can return to the home page',
      noAccessTitle: 'No Access',
      noAccessText: 'Sorry, but you don\'t have permission to access this page',
      goHome: 'Go home',
      footerText: '© 2022 - All Right Reserved',
      loginRegisterError: {
        userNotExistInList: 'User with such email doesn\'t exist. You should register',
        validUser: 'You have entered an invalid username or password',
        userExistInList: 'User with such email already exist',
      },
      login: 'Login',
      registerAndLogin: 'Register and Login',
      save: 'Save',
      cancel: 'Cancel',
      passwordLabel: 'Password',
      firstNameLabel: 'First Name',
      lastNameLabel: 'Last Name',
      registerSuccessfulToast: 'Register and Login Successful',
      loginSuccessfulToast: 'Login Successful',
      nameLabel: 'Name',
      preDescriptionLabel: 'Previous description',
      descriptionLabel: 'Description',
      priceLabel: 'Price',
      currencyLabel: 'Currency',
      brandLabel: 'Brand',
      imagePathLabel: 'Image Path',
      genderLabel: 'Gender',
      typeOfFragranceLabel: 'Type of fragrance',
      availabilityLabel: 'Availability',
      countryOfOriginLabel: 'Country of origin',
      editProduct: 'Edit product',
      addProduct: 'Add product',
      homePageTitle: 'Fresh fragrant confident',
      homePageSubTitle: 'Available premium-quality men\'s and women\'s perfumes, trusted by well-known brands, with proven quality, refresh your day',
      getProduct: 'Get product',
      logIn: 'Log In',
      signUp: 'Sign Up',
      haveNotAccount: 'Don\'t have an account?',
      haveAccount: 'Already have an account?',
      available: 'Available',
      notAvailable: 'Not available',
      noProduct: 'There is no such product',
      homeLink: 'Home',
      storeLink: 'Store',
      loginOut: 'Login Out',
      uaLang: 'UA',
      enLang: 'EN',
      filterLabel: 'Filter by name',
      errorsInput: {
        required: 'This field is required',
        minLength: 'This field should contain at least 5 characters',
        maxLength: 'This field shouldn\'t contain more than 30 characters',
        passwordMinLength: 'This field should contain at least 8 characters',
        weightTest: 'This field should contain only integer or fractional numbers',
        passwordTest: 'Password field should contain at least one letter, one number and one special character',
        emailTest: 'This field should contain a valid email address',
        number: 'This field should contain only numbers',
        priceTest: 'This field should be greater than zero',
        priceMax: 'This field shouldn\'t be greater than 99999',
      },
    }
  },
  ua: {
    translation: {
      cart: 'Кошик',
      'total sum': 'Загальна сума',
      uah: 'грн',
      errorText: 'Сторінка, яку ви шукаєте, може бути перейменована, видалена або взагалі не існувати. Ви можете повернутися на головну сторінку',
      noAccessTitle: 'Немає доступу',
      noAccessText: 'Вибачте, але у вас немає прав для доступу до цієї сторінки',
      goHome: 'На головну сторінку',
      footerText: '© 2022 - Всі Права Захищені',
      loginRegisterError: {
        userNotExistInList: 'Користувача з таким email не існує. Вам необхідно зареєструватися',
        validUser: 'Ви ввели невірне ім\'я користувача або пароль',
        userExistInList: 'Користувач з таким email вже існує',
      },
      login: 'Логін',
      registerAndLogin: 'Реєстрація та вхід',
      save: 'Зберегти',
      cancel: 'Скасувати',
      passwordLabel: 'Пароль',
      firstNameLabel: 'Ім\'я',
      lastNameLabel: 'Прізвище',
      registerSuccessfulToast: 'Реєстрація та вхід успішні',
      loginSuccessfulToast: 'Успішний вхід',
      nameLabel: 'Назва',
      preDescriptionLabel: 'Попередній опис',
      descriptionLabel: 'Опис',
      priceLabel: 'Ціна',
      currencyLabel: 'Валюта',
      brandLabel: 'Бренд',
      imagePathLabel: 'Шлях до зображення',
      genderLabel: 'Стать',
      typeOfFragranceLabel: 'Тип аромату',
      availabilityLabel: 'Наявність',
      countryOfOriginLabel: 'Країна походження',
      editProduct: 'Редагувати товар',
      addProduct: 'Додати товар',
      homePageTitle: 'Свіжий ароматний впевнений',
      homePageSubTitle: 'Доступна чоловіча та жіноча парфумерія преміум-класу, якій довіряють відомі бренди, з перевіреною якістю, освіжить ваш день',
      getProduct: 'Замовити товар',
      logIn: 'Увійти',
      signUp: 'Зареєструватися',
      haveNotAccount: 'Не маєте облікового запису?',
      haveAccount: 'Вже маєте обліковий запис?',
      available: 'Є в наявності',
      notAvailable: 'Немає в наявності',
      noProduct: 'Такого товару не існує',
      homeLink: 'Головна',
      storeLink: 'Магазин',
      loginOut: 'Вийти',
      uaLang: 'УКР',
      enLang: 'АНГЛ',
      filterLabel: 'Фільтрувати за назвою',
      errorsInput: {
        filterLabel: 'Фільтрувати за назвою',
        required: 'Це поле обов\'язкове для заповнення',
        minLength: 'Поле повинно містити не менше 5 символів',
        maxLength: 'Поле не повинно містити більше 30 символів',
        passwordMinLength: 'Це поле повинно містити не менше 8 символів',
        weightTest: 'Це поле повинно містити тільки цілі або дробові числа',
        passwordTest: 'Поле пароля повинно містити принаймні одну літеру, одну цифру та один спеціальний символ',
        emailTest: 'Це поле повинно містити валідну адресу електронної пошти',
        number: 'Поле повинно містити тільки цифри',
        priceTest: 'Це поле повинно бути більше нуля',
        priceMax: 'Це поле не повинно бути більше 99999',
      },
    }
  }
};
